version: '3.8'

services:
  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    command: sh -c "npm install && npm run migrate && npm run dev"
    # command: sh -c "npm install && npm run migrate && npm run seed && npm run dev" # use only intially if you want to seed the berths data in the DB
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file: .env

volumes:
  pgdata:
  